# Generated by Django 5.0.6 on 2024-09-04 06:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=uuid.uuid5, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
